# Site settings
title: R Resources and Tutorials
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/knitr-jekyll" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nDimensional
github_username:  nFrechen
permalink: /:year/:month/:title.html

exclude: ["source", "cache", "knitr-jekyll.Rproj"]

# Build settings
markdown: kramdown
