---
layout: post
title: The annoying nature of predictions
excerpt: How we continuously fail to predict the future and how we tend to ignore this fact.
category: philosophical
language: English
---

What do these things have in common: discoveries, inventions, financial collapse and war? They all appear in history pretty much unpredicted. In retrospect they might seem to have been predictable, but in reality they were not at their time. Instead often inventions stay unnoticed or are ignored for quite a while until people finally realize how useful they are. 

The annoying nature of predictions is above all, that they are mostly wrong. And that is even more striking when we realize, that especially the big unpredicted events are those, that have the biggest impact on our society and our lives. Things that come unpredicted in our lives influence it more than all the tiny things that we predicted. What we can forsee, we can manage, dyke and funnel as we like it to happen. What we failed to predict will roll over us like a hurricane, unstoppable.

Even more annoying, these things are unpredictable per-se: inventions and discoveries are unpredictable because if we could predict them, we would invent or discover them today. Why waiting if we would already know where to search? The other two: financial collapse and war, we would just prevent, if we could predict them. If we knew that the market will collapse in the next hours or days, stakeholders would react accordingly. And this would probably prevent the collapse. On the other hand the announcement of the prediction could cause the collapse in the first place - and it would not have happened without it. If we could exactly predict where and when our enemies will attack, we easily could take counter-measures - and probably prevent the war at all. But history shows that even at the brink of World War I no one certainly knew that a huge war would break out. And nearly all wars hold in common, that people tend to underestimate the length of it.

Of course there are allways people who have predicted it right. Who saw it coming. But first: In our brain we tend to twist our memories in favour of successful predictions (and resulting hig self-esteem). And second: There will allways be someone who predicted something that turned out to happen just that way.

Should we then stop trying to predict things? Of course not! We heavily depend on projecting things into the future! Whether it is small things in our daily lives or big things that we see coming in our distant future. Often it realizes right before our eyes just as we imagined it - as a matter of fact often truly *because* we imagined it. But simply don't be surprised if it turns out differently. And don't be too annoyed about it. That's live! We can't change that.

And by the way: We will never have flying cars! Not in your lifetime! Although they are predicted since ages for the next decade. Erase this prediction from your mind and start imagining something more useful and achievable!
